# Generated by Django 4.0.3 on 2022-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('TVs', 'Телевизоры'), ('notebooks', 'Ноутбуки')], default='other', max_length=11, verbose_name='Категория')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
    ]
