# Generated by Django 4.0.3 on 2022-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='static/img/nophoto.png', null=True, upload_to='user_pics', verbose_name='Картинка'),
        ),
    ]
